### ISSUE TITLE
Beholde fritekstsøk på emneord, eller gjøre om til eksakt?

### ISSUE THREAD

**Issue by stianlagstad** [scriptotek/colligator-backend#16]
Søk på emneord "Solsystemet--utvikling" gir resultater som bare har emneord "utvikling" eller bare emnerord "solsystemet". Is it a feature? Is it a bug? Discuss.

**Comment by danmichaelo** [comment]
Landet på en slags mellomting. Søk er fremdeles ikke 100 % eksakt, men det som er med i søkestrengen må være med. Per https://github.com/scriptotek/colligator-backend/commit/da05e5d2385f6cf9c172193487db9dcf0699f545 gir søk etter "Solsystemet--utvikling" nå kun dokumenter med denne strengen. Men søk etter "Solsystemet" gir også treff i "Solsystemet--utvikling". Det _kan_ være vi vil stramme ytterligere opp i fremtiden, men jeg lukker denne nå.
